config:
  line-length: false
  no-emphasis-as-heading: false
  code-block-style: false
  no-inline-html: false
  ul-style: false
  no-multiple-blanks: false
  no-alt-text: false
  no-bare-urls: false
globs:
  - "**/*.md"
ignores:
  - ".github/**"
  - "proposals/**"
  - ".trestle/**"