matrix:
  - name: Markdown
    sources:
      - '**/*.md'
    default_encoding: utf-8
    aspell:
      lang: en
      d: en_US
    dictionary:
      wordlists:
        - .github/wordlist.txt
      output: wordlist.dic
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
