name: CI
on:
  pull_request:
    branches:
      - "main"
    paths:
      - '**/*.md'
env:
  LC_ALL: en_US.UTF-8
concurrency:
  group: spellcheck-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  spellcheck:
    name: Check spelling
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check spelling
        uses: rojopolis/spellcheck-github-actions@e36f662b21ead3f6f29794ac5c35069bf236463c # v0.37.0
