name: Lint Markdown

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@db43aef879112c3119a410d69f66701e0d530809 # v17.0.0
        with:
          globs: '**/*.md'